Q1: Find the average salary of employees in each department.
Query: SELECT employee_id, AVG(salary) AS avg_salary FROM employees GROUP BY employee_id;

 employee_id |     avg_salary     
-------------+--------------------
           5 | 62000.000000000000
           4 | 75000.000000000000
(2 rows)


Q2: Calculate the total price for each product category.
Query: SELECT product_id, SUM(price) AS total_price FROM products GROUP BY product_id;

 product_id | total_price 
------------+-------------
          3 |       70.00
          5 |        4000
          1 |        1000
(3 rows)


Q3: Determine the maximum and minimum prices of products in the inventory.
Query: SELECT MAX(price) AS max_price, MIN(price) AS min_price FROM products;

 max_price | min_price 
-----------+-----------
      4000 |     70.00
(1 row)


Q4: Count the number of orders placed by each customer.
Query:  SELECT customer_id, COUNT(order_id) AS order_count FROM orders GROUP BY customer_id;

 customer_id | order_count 
-------------+-------------
           2 |           3
           1 |           2
(2 rows)


Q5: Find the total revenue generated by each salesperson.
Query:  SELECT salesperson_id, SUM(total_amount) AS total_revenue FROM orderss 

 salesperson_id | total_revenue 
----------------+---------------
              2 |        600.00
              1 |        250.00
(2 rows)

